### ISSUE TITLE
icon for deathwatch

### ISSUE THREAD

**Issue by jdittrich** [jonathon-love/deathwatch#3]
**Story:** As a user I want to tell apart the different functions of Jamovi easily. 

**Problem:** Death watch uses the generic icon

**Possible Solution:** Design an icon for deathwatch. 

I could take on the task (or peers from opensourcedesign). Do you have any ideas of how an icon for death watch could look like?

**Comment by jonathon-love** [comment]
definitely a skull, or a tombstone, or a tapering survival curve. bonus points for both.

do you know the story behind the walrus logo?

<img width="488" alt="screen shot 2018-12-16 at 08 44 53" src="https://user-images.githubusercontent.com/3240247/50047709-0e71ff80-010f-11e9-9ae9-97ed16e80364.png">

but sure, have a go, just be cognizant of our pallette.

cheers

jonathon

**Comment by jonathon-love** [comment]
oh, and it should be svg

**Comment by jdittrich** [comment]
I tried a bit. It was hard since the pallette does not have death-topic-friendly dark colors :) 

But here my first suggestion,  a curve which is also a coated figure with a  scythe.
![image](https://user-images.githubusercontent.com/3416487/50053229-9832c480-0131-11e9-87d2-2f59a6b40a5a.png)

**Comment by jonathon-love** [comment]
> It was hard since the pallette does not have death-topic-friendly dark colors :)

*chuckles*

that looks great! send it through!

jonathon

**Comment by jdittrich** [comment]
> that looks great!

I can refine the icon in the next days and send a pixel aligned svg.

What is the target size for the icon? (On a normal screen, on high resolution this is less relevant, since sharp anyway)

**Comment by jonathon-love** [comment]
looks to be 45x20

cheers

**Comment by jdittrich** [comment]
I have it ready: 
[deathwatchIcon.zip](https://github.com/jonathon-love/deathwatch/files/2687535/deathwatchIcon.zip)
looking like: 
![deathwatch svg](https://user-images.githubusercontent.com/3416487/50109867-3493be80-0239-11e9-8021-0dec6e2641b1.png)

**Comment by jdittrich** [comment]
Is the icon fine? If there is a problem, ping me

**Comment by jonathon-love** [comment]
oh my bad! i'll put it in the next release!

jonathon

**Comment by jonathon-love** [comment]
oh, can you put CC0 on it again?

with thanks

**Comment by jdittrich** [comment]
I did put the CC0 license in the SVG metadata and included a brief license text in the zip, too:
[deathwatch.zip](https://github.com/jonathon-love/deathwatch/files/2860132/deathwatch.zip)

**Comment by jonathon-love** [comment]
merged!
