### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by jdittrich** [jonathon-love/deathwatch#4]
**Story:** As a potential contributor I like to know under which license the code of deathwatch is. 
**Problem**: Deathwatch seems not to have a license, so legally, normal copyright applies
**Solution**: Put deathwatch under a license like GPL3, BSD or MIT.

**Comment by jonathon-love** [comment]
'tis [here](https://github.com/jonathon-love/deathwatch/blob/master/DESCRIPTION#L9)

**Comment by jdittrich** [comment]
Thanks! Shall we close this, our would you like to add an easy to find LICENSE.md?

**Comment by jonathon-love** [comment]
seems like less work to close it! :)
